name: on push

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      repository: ${{ github.repository }}
      version: 22.04
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
