name: 'On Schedule Base Image Change'

on:
  schedule:
    - cron:  '0 7 1,15 * *'
  workflow_dispatch:

jobs:
  on-schedule-base-image-change:
    strategy:
      matrix:
        branch: ${{ fromJSON(vars.BRANCHES) }}
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Check for base image change'
        id: base-image-change
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: ubuntu:${{ matrix.branch == 'main' && vars.VERSION || matrix.branch }}
          image: ${{ vars.IMAGE }}:${{ matrix.branch == 'main' && vars.VERSION || matrix.branch }}
          platforms: ${{ vars.PLATFORMS }}
      -
        name: 'Checkout repository'
        if: steps.base-image-change.outputs.needs-updating == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      -
        name: 'Build and push image'
        if: steps.base-image-change.outputs.needs-updating == 'true'
        uses: rtvu/build-and-push-to-docker-hub-action@v2
        with:
          image: ${{ vars.IMAGE }}
          latest: ${{ matrix.branch == 'main' }}
          platforms: ${{ vars.PLATFORMS }}
          tags: ${{ matrix.branch == 'main' && vars.VERSION || matrix.branch }}
          token: ${{ secrets.DOCKER_HUB_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
